services:
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: alliano-dev
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: typeorm
    ports:
      - "5432:5432"
    networks:
      - brdidge_network
networks:
  brdidge_network:
    driver: bridge
    